server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
